### ISSUE TITLE
Ensure consistent look and feel across site

### ISSUE THREAD

**Issue by ocassidydev** [The-Carbon-Crushers/greenways#31]
As a user, I want to navigate through the site and have a consistent look and feel to content, forms and other widgets, so that it feels like a cohesive application 

## Requirements

- All pages follow similar style rules, ie. margin, spacing between elements, styling of form elements 

## Tasks

- [ ] Navigate through the site to find any changes needed 
- [ ] Update style.css to make changes
- [x] Larger margins on page edges
- [x] Use flex containers for text content
- [x] Vertical spacing between text content boxes
- [x] Sticky navbar

**Comment by p-rohitt** [comment]
Hey! Is your site deployed?

**Comment by ocassidydev** [comment]
Will be soon
